version: 2.1

jobs:
  chk_npm_lint:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

  chk_npm_test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: npm run test

workflows:
  version: 2
  workflow:
    jobs:
      - chk_npm_lint
      - chk_npm_test
